### PR TITLE
Release 0.6.1 with gl_generator 0.14

### PR DESCRIPTION
**Pull request by alexheretic**

### CODE REVIEW

**Review by kvark — APPROVED** [review]
I assume the produced API is backwards compatible? How do we make sure it's the case?

**Comment by alexheretic** [comment]
I believe so. I'll run a diff on the generated code when I get a chance to double check.

**Comment by alexheretic** [comment]
_`GLDEBUGPROC`, `GLDEBUGPROCARB`, `GLDEBUGPROCKHR`, `GLDEBUGPROCAMD`_ types are now wrapped in options. I don't believe these are being used by _gfx_device_gl_.

## gl_bindings.rs diff
```patch
--- /home/alex/tmp/gl_bindings-master.rs	2020-02-03 20:21:12.323784692 +0000
+++ /home/alex/tmp/gl_bindings-gg-0.14.rs	2020-02-03 20:22:05.380487349 +0000
@@ -57,27 +57,27 @@
 pub enum _cl_context {}
 pub enum _cl_event {}
 
-pub type GLDEBUGPROC = extern "system" fn(source: GLenum,
+pub type GLDEBUGPROC = Option<extern "system" fn(source: GLenum,
                                           gltype: GLenum,
                                           id: GLuint,
                                           severity: GLenum,
                                           length: GLsizei,
                                           message: *const GLchar,
-                                          userParam: *mut super::__gl_imports::raw::c_void);
-pub type GLDEBUGPROCARB = extern "system" fn(source: GLenum,
+                                                 userParam: *mut super::__gl_imports::raw::c_void)>;
+pub type GLDEBUGPROCARB = Option<extern "system" fn(source: GLenum,
                                              gltype: GLenum,
                                              id: GLuint,
                                              severity: GLenum,
                                              length: GLsizei,
                                              message: *const GLchar,
-                                             userParam: *mut super::__gl_imports::raw::c_void);
-pub type GLDEBUGPROCKHR = extern "system" fn(source: GLenum,
+                                                    userParam: *mut super::__gl_imports::raw::c_void)>;
+pub type GLDEBUGPROCKHR = Option<extern "system" fn(source: GLenum,
                                              gltype: GLenum,
                                              id: GLuint,
                                              severity: GLenum,
                                              length: GLsizei,
                                              message: *const GLchar,
-                                             userParam: *mut super::__gl_imports::raw::c_void);
+                                                    userParam: *mut super::__gl_imports::raw::c_void)>;
 
 // GLES 1 types
 // "pub type GLclampx = i32;",
@@ -109,12 +109,12 @@
 // GLES 2 types (none currently)
 
 // Vendor extension types
-pub type GLDEBUGPROCAMD = extern "system" fn(id: GLuint,
+pub type GLDEBUGPROCAMD = Option<extern "system" fn(id: GLuint,
                                              category: GLenum,
                                              severity: GLenum,
                                              length: GLsizei,
                                              message: *const GLchar,
-                                             userParam: *mut super::__gl_imports::raw::c_void);
+                                                    userParam: *mut super::__gl_imports::raw::c_void)>;
 pub type GLhalfNV = super::__gl_imports::raw::c_ushort;
 pub type GLvdpauSurfaceNV = GLintptr;
 
@@ -2616,7 +2616,7 @@
             #[allow(dead_code, unused_variables)]
             pub fn load_with<F>(mut loadfn: F) -> Gl where F: FnMut(&'static str) -> *const __gl_imports::raw::c_void {
                 #[inline(never)]
-                fn do_metaloadfn(loadfn: &mut FnMut(&'static str) -> *const __gl_imports::raw::c_void,
+                fn do_metaloadfn(loadfn: &mut dyn FnMut(&'static str) -> *const __gl_imports::raw::c_void,
                                  symbol: &'static str,
                                  symbols: &[&'static str])
                                  -> *const __gl_imports::raw::c_void {
```

**Comment by kvark** [comment]
amazing work, thanks!
bors r+

**Comment by kvark** [comment]
Published now!

**Pull request merged**
